spring:
  application:
    name: customer-service

  datasource:
    url: ${CUSTOMER_DB_URL:jdbc:oracle:thin:@//localhost:1521/FREEPDB1}
    username: ${CUSTOMER_DB_USERNAME:BANK_CUSTOMER}
    password: ${CUSTOMER_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info