services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: banking-oracle
    restart: unless-stopped

    ports:
      - "1521:1521"

    environment:
      ORACLE_PWD: ${ORACLE_PASSWORD}
      BANK_IDENTITY_PASSWORD: ${BANK_IDENTITY_PASSWORD}
      BANK_CUSTOMER_PASSWORD: ${BANK_CUSTOMER_PASSWORD}
      BANK_ACCOUNT_PASSWORD: ${BANK_ACCOUNT_PASSWORD}
      BANK_TRANSFER_PASSWORD: ${BANK_TRANSFER_PASSWORD}
      BANK_AUDIT_PASSWORD: ${BANK_AUDIT_PASSWORD}

    volumes:
      - banking-oracle-data:/opt/oracle/oradata
      - ./init:/opt/oracle/scripts/startup:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/$$ORACLE_PWD@localhost:1521/FREEPDB1 || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

volumes:
  banking-oracle-data:
    name: banking-oracle-data