#!/bin/bash
set -e

sqlplus -s "/ as sysdba" <<EOF

WHENEVER SQLERROR EXIT SQL.SQLCODE;

ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'BANK_IDENTITY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER BANK_IDENTITY IDENTIFIED BY "${BANK_IDENTITY_PASSWORD}"';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO BANK_IDENTITY';
    EXECUTE IMMEDIATE 'ALTER USER BANK_IDENTITY QUOTA UNLIMITED ON USERS';
  END IF;

  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'BANK_CUSTOMER';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER BANK_CUSTOMER IDENTIFIED BY "${BANK_CUSTOMER_PASSWORD}"';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO BANK_CUSTOMER';
    EXECUTE IMMEDIATE 'ALTER USER BANK_CUSTOMER QUOTA UNLIMITED ON USERS';
  END IF;

  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'BANK_ACCOUNT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER BANK_ACCOUNT IDENTIFIED BY "${BANK_ACCOUNT_PASSWORD}"';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO BANK_ACCOUNT';
    EXECUTE IMMEDIATE 'ALTER USER BANK_ACCOUNT QUOTA UNLIMITED ON USERS';
  END IF;

  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'BANK_TRANSFER';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER BANK_TRANSFER IDENTIFIED BY "${BANK_TRANSFER_PASSWORD}"';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO BANK_TRANSFER';
    EXECUTE IMMEDIATE 'ALTER USER BANK_TRANSFER QUOTA UNLIMITED ON USERS';
  END IF;

  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'BANK_AUDIT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER BANK_AUDIT IDENTIFIED BY "${BANK_AUDIT_PASSWORD}"';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO BANK_AUDIT';
    EXECUTE IMMEDIATE 'ALTER USER BANK_AUDIT QUOTA UNLIMITED ON USERS';
  END IF;
END;
/

EXIT;
EOF